vim.lsp.enable({
    'clangd',
    'omnisharp',
    'nixd',
    -- 'denols',
    'dockerls',
    -- 'graphql',
    -- 'haskell-language-server',
    -- 'java_language_server',
    'html',
    'cssls',
    'jsonls',
    'eslint',
    'kotlin_language_server',
    -- 'lua_ls',
    -- 'marksman',
    'pyright',
    -- 'sqlls',
    -- 'texlab',
    'ts_ls',
    -- 'volar',
})
