-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#1a110f',
  base01 = '#140c0a',
  base02 = '#231917',
  base03 = '#53433f',
  base04 = '#d8c2bb',
  base05 = '#f1dfda',
  base06 = '#392e2b',
  base07 = '#423733',

  base08 = '#ffb4ab',
  base09 = '#d7c68d',
  base0A = '#e7bdb0',
  base0B = '#ffb59d',
  base0C = '#51461a',
  base0D = '#723520',
  base0E = '#5d4036',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#723520',
  fg = '#1a110f',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#f4e2a7',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d7c68d',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e7bdb0',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#8f4c35',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#140c0a',
  fg = '#ffb59d',
})
