# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct 12 18:52:27 2025
# ------------------------------------------------

package:
  name: libffi
  version: 3.5.2
source:
  url: https://github.com/libffi/libffi/releases/download/v3.5.2/libffi-3.5.2.tar.gz
  sha256: f3a3082a23b37c293a4fcd1053147b371f2ff91fa7ea1b2a52e335676bac82dc
  patches:
    - 0001-arm64-use-a-dedicated-dylib-for-trampolines-so-it-ca.patch
    - 0002-Add-support-for-ffi_find_closure_for_code_np-on-Appl.patch
build:
  number: '0'
  run_exports:
    - libffi >=3.5.2,<3.6.0a0
  string: h9ec8514_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.72 pl5321hbb4ee43_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - gcc_impl_linux-64 14.3.0 hd9e9e21_7
    - gcc_linux-64 14.3.0 h298d278_12
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libgcc 15.2.0 h767d61c_7
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_107
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - libltdl 2.4.3a h5888daf_0
    - libsanitizer 14.3.0 hd08acf3_7
    - libstdcxx 15.2.0 h8f9b012_7
    - libtool 2.5.4 h5888daf_0
    - libxcrypt 4.4.36 hd590300_1
    - m4 1.4.20 hb9d3cd8_0
    - make 4.4.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - patch 2.8 hb03c661_1002
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.17 h0157908_18
    - texinfo 7.2 pl5321haa1a288_0
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.2.0 h767d61c_7
    - libgomp 15.2.0 h767d61c_7
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
test:
  requires: null
  commands:
    - test -e $PREFIX/lib/libffi${SHLIB_EXT}
    - test -e $PREFIX/lib/libffi.a
    - test -e $PREFIX/include/ffi.h
    - test -e $PREFIX/include/ffitarget.h
about:
  home: https://sourceware.org/libffi/
  license: MIT
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library.
  description: 'The libffi library provides a portable, high level programming interface

    to various calling conventions. This allows a programmer to call any

    function specified by a call interface description at run-time.

    '
  doc_url: https://sourceware.org/libffi/
  dev_url: https://github.com/libffi/libffi
extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - stefan-balke
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251012.3.1
  remote_url: https://github.com/conda-forge/libffi-feedstock
  sha: 3eba65799142716bceeda38efa8cdd58fd3bd962
