# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.7
source:
  sha256: 37d7284556b20954e56e1ca85b80226768902e2edabd3b649e9e72c0c9012ee3
  url: https://github.com/facebook/zstd/archive/v1.5.7.tar.gz
build:
  number: 2
  run_exports:
    - zstd >=1.5.7,<1.6.0a0
  string: hb8e6e7a_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - cmake-no-system 3.31.6 h5888daf_0
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 hc28eda2_8
    - gxx_impl_linux-64 13.3.0 hae580e1_2
    - gxx_linux-64 13.3.0 h6834431_8
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libgcc 14.2.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - libsanitizer 13.3.0 he8ea267_2
    - libstdcxx 14.2.0 h8f9b012_2
    - libstdcxx-devel_linux-64 13.3.0 hc03c837_102
    - libstdcxx-ng 14.2.0 h4852527_2
    - make 4.4.1 hb9d3cd8_2
    - ninja 1.12.1 h297d8ca_0
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025a h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 14.2.0 h767d61c_2
    - libgomp 14.2.0 h767d61c_2
    - libstdcxx 14.2.0 h8f9b012_2
    - libzlib 1.3.1 hb9d3cd8_2
    - zlib 1.3.1 hb9d3cd8_2
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - libstdcxx >=13
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libzstd.so
    - test ! -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/include/zstd.h
    - zstd -be -i5
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags libzstd
    - cd cf_test
    - cmake $CMAKE_ARGS .
  files:
    - cf_test/
  requires:
    - cmake
    - gcc_linux-64 13.*
    - make
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  feedstock-name: zstd
  final: true
  flow_run_id: azure_20250319.1.1
  recipe-maintainers:
    - JohanMabille
    - hmaarrfk
    - msarahan
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstd-feedstock
  sha: 93b16964779c72e6ae2654734a553255c4e1aab3
