# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: ld_impl_linux-64
  version: '2.44'
source:
  - patches:
      - patches/0001-fallback-sysroot.diff
    sha256: f66390a661faa117d00fab2e79cf2dc9d097b42cc296bf3f8677d1e7b452dc3a
    url:
      - https://ftp.gnu.org/gnu/binutils/binutils-2.44.tar.bz2
      - https://mirrors.ocf.berkeley.edu/gnu/binutils/binutils-2.44.tar.bz2
build:
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - gcc_bootstrap_linux-64 14.*
  merge_build_host: false
  number: 4
  string: h1aa0949_4
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - gcc_bootstrap_linux-64 14.3.0 he3b26db_12
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - pkg-config 0.29.2 h4bc722e_1009
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.2.0 h767d61c_7
    - libgomp 15.2.0 h767d61c_7
    - libstdcxx 15.2.0 h8f9b012_7
    - libzlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - __glibc >=2.17,<3.0.a0
    - zstd >=1.5.7,<1.6.0a0
  run_constrained:
    - binutils_impl_linux-64 2.44
test:
  commands:
    - x86_64-conda-linux-gnu-ld --help
    - echo "conda"
about:
  home: https://www.gnu.org/software/binutils/
  license: GPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LIB
    - COPYING3
    - COPYING3.LIB
  summary: 'A set of programming tools for creating and managing binary programs,
    object files,

    libraries, profile data, and assembly source code.

    '
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20251024.2.1
  recipe-maintainers:
    - beckermr
    - frol
    - isuruf
    - jjhelmus
  remote_url: https://github.com/conda-forge/binutils-feedstock
  sha: a2d1b358b28f206000978d427004457d253b1c13
