# autogenerated by txs
\addto{arg1}{arg2}#S
\babel#S
\babeladdtranslations{arg1}{arg2}#S
\ccClassWarning{arg1}#S
\ccaddto#S
\ccaddtoINDOC{arg1}{arg2}{arg3}#S
\ccaddtonow{arg1}{arg2}#S
\ccaddto{arg1}{arg2}{arg3}#S
\condbreak{arg1}#S
\csname#S
\enumerate#S
\newwarning{arg1}{arg2}#S
\numberallwithin{arg1}#S
