# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f1dedc"

# Title color for boxes
theme[title]="#ffb4ac"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e7bdb8"

# Background color of selected item in processes box
theme[selected_bg]="#ffb4ac"

# Foreground color of selected item in processes box
theme[selected_fg]="#561e1a"

# Color of inactive/disabled text
theme[inactive_fg]="#d8c2bf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e0c38c"

# Cpu box outline color
theme[cpu_box]="#a08c8a"

# Memory/disks box outline color
theme[mem_box]="#a08c8a"

# Net up/down box outline color
theme[net_box]="#a08c8a"

# Processes box outline color
theme[proc_box]="#a08c8a"

# Box divider line and small boxes line color
theme[div_line]="#534341"

# Temperature graph colors
theme[temp_start]="#e7bdb8"
theme[temp_mid]="#ffb4ac"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e7bdb8"
theme[cpu_mid]="#ffb4ac"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e7bdb8"
theme[free_mid]=""
theme[free_end]="#5d3f3c"

# Mem/Disk cached meter
theme[cached_start]="#e0c38c"
theme[cached_mid]=""
theme[cached_end]="#584419"

# Mem/Disk available meter
theme[available_start]="#ffb4ac"
theme[available_mid]=""
theme[available_end]="#73332e"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e7bdb8"
theme[download_mid]="#ffb4ac"
theme[download_end]="#e0c38c"

# Upload graph colors
theme[upload_start]="#e7bdb8"
theme[upload_mid]="#ffb4ac"
theme[upload_end]="#e0c38c"
