# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f1dfdc"

# Title color for boxes
theme[title]="#ffb4a8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e7bdb6"

# Background color of selected item in processes box
theme[selected_bg]="#ffb4a8"

# Foreground color of selected item in processes box
theme[selected_fg]="#561e17"

# Color of inactive/disabled text
theme[inactive_fg]="#d8c2be"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#dec48c"

# Cpu box outline color
theme[cpu_box]="#a08c89"

# Memory/disks box outline color
theme[mem_box]="#a08c89"

# Net up/down box outline color
theme[net_box]="#a08c89"

# Processes box outline color
theme[proc_box]="#a08c89"

# Box divider line and small boxes line color
theme[div_line]="#534341"

# Temperature graph colors
theme[temp_start]="#e7bdb6"
theme[temp_mid]="#ffb4a8"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e7bdb6"
theme[cpu_mid]="#ffb4a8"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e7bdb6"
theme[free_mid]=""
theme[free_end]="#5d3f3b"

# Mem/Disk cached meter
theme[cached_start]="#dec48c"
theme[cached_mid]=""
theme[cached_end]="#564419"

# Mem/Disk available meter
theme[available_start]="#ffb4a8"
theme[available_mid]=""
theme[available_end]="#73342b"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e7bdb6"
theme[download_mid]="#ffb4a8"
theme[download_end]="#dec48c"

# Upload graph colors
theme[upload_start]="#e7bdb6"
theme[upload_mid]="#ffb4a8"
theme[upload_end]="#dec48c"
