{ self, inputs, ... }:
{
  perSystem =
    { pkgs, ... }:
    let
      colorChangeScript = pkgs.writeShellScript "color-change" ''
        COLORS_FILE="$HOME/.config/noctalia/colors.json"
        KITTY_THEME_FILE="$HOME/.config/kitty/current-theme.conf"

        if [ ! -f "$COLORS_FILE" ]; then
          exit 0
        fi

        # Extract colors using jq
        PRIMARY=$(${pkgs.jq}/bin/jq -r '.mPrimary' "$COLORS_FILE")
        ON_PRIMARY=$(${pkgs.jq}/bin/jq -r '.mOnPrimary' "$COLORS_FILE")
        SECONDARY=$(${pkgs.jq}/bin/jq -r '.mSecondary' "$COLORS_FILE")
        ON_SECONDARY=$(${pkgs.jq}/bin/jq -r '.mOnSecondary' "$COLORS_FILE")
        TERTIARY=$(${pkgs.jq}/bin/jq -r '.mTertiary' "$COLORS_FILE")
        ON_TERTIARY=$(${pkgs.jq}/bin/jq -r '.mOnTertiary' "$COLORS_FILE")
        SURFACE=$(${pkgs.jq}/bin/jq -r '.mSurface' "$COLORS_FILE")
        ON_SURFACE=$(${pkgs.jq}/bin/jq -r '.mOnSurface' "$COLORS_FILE")
        SURFACE_VARIANT=$(${pkgs.jq}/bin/jq -r '.mSurfaceVariant' "$COLORS_FILE")
        ON_SURFACE_VARIANT=$(${pkgs.jq}/bin/jq -r '.mOnSurfaceVariant' "$COLORS_FILE")
        HOVER=$(${pkgs.jq}/bin/jq -r '.mHover' "$COLORS_FILE")
        ON_HOVER=$(${pkgs.jq}/bin/jq -r '.mOnHover' "$COLORS_FILE")
        ERROR=$(${pkgs.jq}/bin/jq -r '.mError' "$COLORS_FILE")

        # Write to current-theme.conf
        cat <<EOF > "$KITTY_THEME_FILE"
# Generated by Noctalia colorscheme sync hook
color0 #45475a
color1 $ERROR
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #f5c2e7
color6 $TERTIARY
color7 #a6adc8
color8 #585b70
color9 $ERROR
color10 #89d88b
color11 #ebd391
color12 #74a8fc
color13 #f2aede
color14 $TERTIARY
color15 #bac2de

background $SURFACE
foreground $ON_SURFACE
selection_foreground $ON_SURFACE
cursor $PRIMARY
cursor_text_color $SURFACE
selection_background $SURFACE_VARIANT
active_border_color $PRIMARY
inactive_border_color $SECONDARY

active_tab_foreground   $ON_PRIMARY
active_tab_background   $PRIMARY
inactive_tab_foreground $ON_SURFACE_VARIANT
inactive_tab_background $SURFACE_VARIANT
cursor_trail_color      $ON_SURFACE_VARIANT
EOF

        # Write to noctalia.kdl for Niri
        NIRI_THEME_FILE="$HOME/.config/niri/noctalia.kdl"
        if [ -d "$HOME/.config/niri" ]; then
          cat <<EOF > "$NIRI_THEME_FILE"
// Generated by Noctalia colorscheme sync hook
layout {
    border {
        on
        active-color "$PRIMARY"
        inactive-color "$SECONDARY"
    }
    focus-ring {
        active-color "$PRIMARY"
        inactive-color "$SECONDARY"
    }
}
EOF
          # Reload niri configuration
          ${pkgs.niri}/bin/niri msg action reload-config 2>/dev/null || true
        fi

        # Reload kitty
        ${pkgs.killall}/bin/killall -USR1 kitty 2>/dev/null || true
      '';
    in
    {
      packages.myNoctalia = inputs.wrapper-modules.wrappers.noctalia-shell.wrap {
        inherit pkgs;
        settings =
          let
            jsonSettings = builtins.fromJSON (builtins.readFile ./noctalia/settings.json);
            overrides = {
              hooks = {
                enabled = true;
                colorGeneration = "${colorChangeScript}";
              };
            };
          in
          pkgs.lib.recursiveUpdate jsonSettings overrides;
        outOfStoreConfig = "/home/umut/.config/noctalia";
      };
    };
}
